apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
  namespace: default
  labels:
    app: backend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        lingo.substratus.ai/models: backend
    spec:
      containers:
        - name: backend
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /get
              port: 80
