apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  annotations:
    lingo.substratus.ai/deployment: backend-deployment
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
